# Header
menu:
  Home: /
  About: /about/
  Archives: /archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-47671402-1
favicon: /favicon.png

# Social Graph
twitter: Ohyama_
fb_admins: 1798376677
